// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class AmbientMode
    {
        public static readonly string Constant = "Constant";
        public static readonly string Flat = "Flat";
        public static readonly string Directional = "Directional";
    }
}
