// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class AnimatedModel: UnityToRebelFork.Editor.StaticModel
    {
        protected static readonly RbfxAttribute<bool> UpdateWhenInvisibleAttr = new ("Update When Invisible", VariantType.VarBool, new Variant(false), _=>((AnimatedModel)_).UpdateWhenInvisible, (_,v)=>((AnimatedModel)_).UpdateWhenInvisible = v);
        protected static readonly RbfxAttribute<float> AnimationLODBiasAttr = new ("Animation LOD Bias", VariantType.VarFloat, new Variant(1f), _=>((AnimatedModel)_).AnimationLODBias, (_,v)=>((AnimatedModel)_).AnimationLODBias = v);
        protected static readonly RbfxAttribute<VariantList> BoneAnimationEnabledAttr = new ("Bone Animation Enabled", VariantType.VarVariantList, new Variant(new VariantList() {  }), _=>((AnimatedModel)_).BoneAnimationEnabled, (_,v)=>((AnimatedModel)_).BoneAnimationEnabled = v);
        protected static readonly RbfxAttribute<Buffer> MorphsAttr = new ("Morphs", VariantType.VarBuffer, new Variant(new Buffer()), _=>((AnimatedModel)_).Morphs, (_,v)=>((AnimatedModel)_).Morphs = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return UpdateWhenInvisibleAttr;
            yield return AnimationLODBiasAttr;
            yield return BoneAnimationEnabledAttr;
            yield return MorphsAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _updateWhenInvisible = false;

        protected float _animationLODBias = 1f;

        protected VariantList _boneAnimationEnabled = new VariantList() {  };

        protected Buffer _morphs = new Buffer();

        public bool UpdateWhenInvisible
        {
            get => _updateWhenInvisible;
            set => _updateWhenInvisible = value;
        }

        public float AnimationLODBias
        {
            get => _animationLODBias;
            set => _animationLODBias = value;
        }

        public VariantList BoneAnimationEnabled
        {
            get => _boneAnimationEnabled;
            set => _boneAnimationEnabled = value;
        }

        public Buffer Morphs
        {
            get => _morphs;
            set => _morphs = value;
        }
    }
}
