// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class AnimatedSprite2D: UnityToRebelFork.Editor.StaticSprite2D
    {
        protected static readonly RbfxAttribute<float> SpeedAttr = new ("Speed", VariantType.VarFloat, new Variant(1f), _=>((AnimatedSprite2D)_).Speed, (_,v)=>((AnimatedSprite2D)_).Speed = v);
        protected static readonly RbfxAttribute<string> EntityAttr = new ("Entity", VariantType.VarString, new Variant(""), _=>((AnimatedSprite2D)_).Entity, (_,v)=>((AnimatedSprite2D)_).Entity = v);
        protected static readonly RbfxAttribute<ResourceRef> AnimationSetAttr = new ("Animation Set", VariantType.VarResourceRef, new Variant(new ResourceRef("AnimatedSprite2D", "")), _=>((AnimatedSprite2D)_).AnimationSet, (_,v)=>((AnimatedSprite2D)_).AnimationSet = v);
        protected static readonly RbfxAttribute<string> AnimationAttr = new ("Animation", VariantType.VarString, new Variant(""), _=>((AnimatedSprite2D)_).Animation, (_,v)=>((AnimatedSprite2D)_).Animation = v);
        protected static readonly RbfxAttribute<string> LoopModeAttr = new ("Loop Mode", VariantType.VarString, new Variant(UnityToRebelFork.Editor.LoopMode.Default), _=>((AnimatedSprite2D)_).LoopMode, (_,v)=>((AnimatedSprite2D)_).LoopMode = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return SpeedAttr;
            yield return EntityAttr;
            yield return AnimationSetAttr;
            yield return AnimationAttr;
            yield return LoopModeAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected float _speed = 1f;

        protected string _entity = "";

        protected ResourceRef _animationSet = new ResourceRef("AnimatedSprite2D", "");

        protected string _animation = "";

        protected string _loopMode = UnityToRebelFork.Editor.LoopMode.Default;

        public float Speed
        {
            get => _speed;
            set => _speed = value;
        }

        public string Entity
        {
            get => _entity;
            set => _entity = value;
        }

        public ResourceRef AnimationSet
        {
            get => _animationSet;
            set => _animationSet = value;
        }

        public string Animation
        {
            get => _animation;
            set => _animation = value;
        }

        public string LoopMode
        {
            get => _loopMode;
            set => _loopMode = value;
        }
    }
}
