// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class AutoremoveMode
    {
        public static readonly string Disabled = "Disabled";
        public static readonly string Component = "Component";
        public static readonly string Node = "Node";
    }
}
