// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class BlendMode
    {
        public static readonly string replace = "replace";
        public static readonly string add = "add";
        public static readonly string multiply = "multiply";
        public static readonly string alpha = "alpha";
        public static readonly string addalpha = "addalpha";
        public static readonly string premulalpha = "premulalpha";
        public static readonly string invdestalpha = "invdestalpha";
        public static readonly string subtract = "subtract";
        public static readonly string subtractalpha = "subtractalpha";
        public static readonly string decal = "decal";
    }
}
