// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class BodyType
    {
        public static readonly string Static = "Static";
        public static readonly string Kinematic = "Kinematic";
        public static readonly string Dynamic = "Dynamic";
    }
}
