// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class CollisionEventMode
    {
        public static readonly string Never = "Never";
        public static readonly string WhenActive = "When Active";
        public static readonly string Always = "Always";
    }
}
