// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class CollisionChain2D: UnityToRebelFork.Editor.CollisionShape2D
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((CollisionChain2D)_).IsEnabled, (_,v)=>((CollisionChain2D)_).IsEnabled = v);
        protected static readonly RbfxAttribute<bool> LoopAttr = new ("Loop", VariantType.VarBool, new Variant(false), _=>((CollisionChain2D)_).Loop, (_,v)=>((CollisionChain2D)_).Loop = v);
        protected static readonly RbfxAttribute<Buffer> VerticesAttr = new ("Vertices", VariantType.VarBuffer, new Variant(new Buffer()), _=>((CollisionChain2D)_).Vertices, (_,v)=>((CollisionChain2D)_).Vertices = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return LoopAttr;
            yield return VerticesAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected bool _loop = false;

        protected Buffer _vertices = new Buffer();

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public bool Loop
        {
            get => _loop;
            set => _loop = value;
        }

        public Buffer Vertices
        {
            get => _vertices;
            set => _vertices = value;
        }
    }
}
