// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class CollisionPolygon2D: UnityToRebelFork.Editor.CollisionShape2D
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((CollisionPolygon2D)_).IsEnabled, (_,v)=>((CollisionPolygon2D)_).IsEnabled = v);
        protected static readonly RbfxAttribute<Buffer> VerticesAttr = new ("Vertices", VariantType.VarBuffer, new Variant(new Buffer()), _=>((CollisionPolygon2D)_).Vertices, (_,v)=>((CollisionPolygon2D)_).Vertices = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return VerticesAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected Buffer _vertices = new Buffer();

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public Buffer Vertices
        {
            get => _vertices;
            set => _vertices = value;
        }
    }
}
