// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class ColorSpace
    {
        public static readonly string LDRGamma = "LDR Gamma";
        public static readonly string LDRLinear = "LDR Linear";
        public static readonly string HDRLinear = "HDR Linear";
        public static readonly string Optimized = "Optimized";
    }
}
