// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class ConstraintType
    {
        public static readonly string Point = "Point";
        public static readonly string Hinge = "Hinge";
        public static readonly string Slider = "Slider";
        public static readonly string ConeTwist = "ConeTwist";
    }
}
