// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class ConstraintRope2D: UnityToRebelFork.Editor.Constraint2D
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((ConstraintRope2D)_).IsEnabled, (_,v)=>((ConstraintRope2D)_).IsEnabled = v);
        protected static readonly RbfxAttribute<Vector2> OwnerBodyAnchorAttr = new ("Owner Body Anchor", VariantType.VarVector2, new Variant(new Vector2(0f, 0f)), _=>((ConstraintRope2D)_).OwnerBodyAnchor, (_,v)=>((ConstraintRope2D)_).OwnerBodyAnchor = v);
        protected static readonly RbfxAttribute<Vector2> OtherBodyAnchorAttr = new ("Other Body Anchor", VariantType.VarVector2, new Variant(new Vector2(0f, 0f)), _=>((ConstraintRope2D)_).OtherBodyAnchor, (_,v)=>((ConstraintRope2D)_).OtherBodyAnchor = v);
        protected static readonly RbfxAttribute<float> MaxLengthAttr = new ("Max Length", VariantType.VarFloat, new Variant(0f), _=>((ConstraintRope2D)_).MaxLength, (_,v)=>((ConstraintRope2D)_).MaxLength = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return OwnerBodyAnchorAttr;
            yield return OtherBodyAnchorAttr;
            yield return MaxLengthAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected Vector2 _ownerBodyAnchor = new Vector2(0f, 0f);

        protected Vector2 _otherBodyAnchor = new Vector2(0f, 0f);

        protected float _maxLength = 0f;

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public Vector2 OwnerBodyAnchor
        {
            get => _ownerBodyAnchor;
            set => _ownerBodyAnchor = value;
        }

        public Vector2 OtherBodyAnchor
        {
            get => _otherBodyAnchor;
            set => _otherBodyAnchor = value;
        }

        public float MaxLength
        {
            get => _maxLength;
            set => _maxLength = value;
        }
    }
}
