// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class ConstraintGear2D: UnityToRebelFork.Editor.Constraint2D
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((ConstraintGear2D)_).IsEnabled, (_,v)=>((ConstraintGear2D)_).IsEnabled = v);
        protected static readonly RbfxAttribute<float> RatioAttr = new ("Ratio", VariantType.VarFloat, new Variant(0f), _=>((ConstraintGear2D)_).Ratio, (_,v)=>((ConstraintGear2D)_).Ratio = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return RatioAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected float _ratio = 0f;

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public float Ratio
        {
            get => _ratio;
            set => _ratio = value;
        }
    }
}
