// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class Constraint2D: UnityToRebelFork.Editor.Component
    {
        protected static readonly RbfxAttribute<bool> CollideConnectedAttr = new ("Collide Connected", VariantType.VarBool, new Variant(false), _=>((Constraint2D)_).CollideConnected, (_,v)=>((Constraint2D)_).CollideConnected = v);
        protected static readonly RbfxAttribute<int> OtherBodyNodeIDAttr = new ("Other Body NodeID", VariantType.VarInt, new Variant(0), _=>((Constraint2D)_).OtherBodyNodeID, (_,v)=>((Constraint2D)_).OtherBodyNodeID = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return CollideConnectedAttr;
            yield return OtherBodyNodeIDAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _collideConnected = false;

        protected int _otherBodyNodeID = 0;

        public bool CollideConnected
        {
            get => _collideConnected;
            set => _collideConnected = value;
        }

        public int OtherBodyNodeID
        {
            get => _otherBodyNodeID;
            set => _otherBodyNodeID = value;
        }
    }
}
