// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class ConstraintWeld2D: UnityToRebelFork.Editor.Constraint2D
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((ConstraintWeld2D)_).IsEnabled, (_,v)=>((ConstraintWeld2D)_).IsEnabled = v);
        protected static readonly RbfxAttribute<Vector2> AnchorAttr = new ("Anchor", VariantType.VarVector2, new Variant(new Vector2(0f, 0f)), _=>((ConstraintWeld2D)_).Anchor, (_,v)=>((ConstraintWeld2D)_).Anchor = v);
        protected static readonly RbfxAttribute<float> FrequencyHzAttr = new ("Frequency Hz", VariantType.VarFloat, new Variant(0f), _=>((ConstraintWeld2D)_).FrequencyHz, (_,v)=>((ConstraintWeld2D)_).FrequencyHz = v);
        protected static readonly RbfxAttribute<float> DampingRatioAttr = new ("Damping Ratio", VariantType.VarFloat, new Variant(0f), _=>((ConstraintWeld2D)_).DampingRatio, (_,v)=>((ConstraintWeld2D)_).DampingRatio = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return AnchorAttr;
            yield return FrequencyHzAttr;
            yield return DampingRatioAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected Vector2 _anchor = new Vector2(0f, 0f);

        protected float _frequencyHz = 0f;

        protected float _dampingRatio = 0f;

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public Vector2 Anchor
        {
            get => _anchor;
            set => _anchor = value;
        }

        public float FrequencyHz
        {
            get => _frequencyHz;
            set => _frequencyHz = value;
        }

        public float DampingRatio
        {
            get => _dampingRatio;
            set => _dampingRatio = value;
        }
    }
}
