// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class CrowdManager: UnityToRebelFork.Editor.Component
    {
        protected static readonly RbfxAttribute<int> MaxAgentsAttr = new ("Max Agents", VariantType.VarInt, new Variant(512), _=>((CrowdManager)_).MaxAgents, (_,v)=>((CrowdManager)_).MaxAgents = v);
        protected static readonly RbfxAttribute<float> MaxAgentRadiusAttr = new ("Max Agent Radius", VariantType.VarFloat, new Variant(0f), _=>((CrowdManager)_).MaxAgentRadius, (_,v)=>((CrowdManager)_).MaxAgentRadius = v);
        protected static readonly RbfxAttribute<int> NavigationMeshAttr = new ("Navigation Mesh", VariantType.VarInt, new Variant(0), _=>((CrowdManager)_).NavigationMesh, (_,v)=>((CrowdManager)_).NavigationMesh = v);
        protected static readonly RbfxAttribute<VariantList> FilterTypesAttr = new ("Filter Types", VariantType.VarVariantList, new Variant(new VariantList() {  }), _=>((CrowdManager)_).FilterTypes, (_,v)=>((CrowdManager)_).FilterTypes = v);
        protected static readonly RbfxAttribute<VariantList> ObstacleAvoidanceTypesAttr = new ("Obstacle Avoidance Types", VariantType.VarVariantList, new Variant(new VariantList() {  }), _=>((CrowdManager)_).ObstacleAvoidanceTypes, (_,v)=>((CrowdManager)_).ObstacleAvoidanceTypes = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return MaxAgentsAttr;
            yield return MaxAgentRadiusAttr;
            yield return NavigationMeshAttr;
            yield return FilterTypesAttr;
            yield return ObstacleAvoidanceTypesAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected int _maxAgents = 512;

        protected float _maxAgentRadius = 0f;

        protected int _navigationMesh = 0;

        protected VariantList _filterTypes = new VariantList() {  };

        protected VariantList _obstacleAvoidanceTypes = new VariantList() {  };

        public int MaxAgents
        {
            get => _maxAgents;
            set => _maxAgents = value;
        }

        public float MaxAgentRadius
        {
            get => _maxAgentRadius;
            set => _maxAgentRadius = value;
        }

        public int NavigationMesh
        {
            get => _navigationMesh;
            set => _navigationMesh = value;
        }

        public VariantList FilterTypes
        {
            get => _filterTypes;
            set => _filterTypes = value;
        }

        public VariantList ObstacleAvoidanceTypes
        {
            get => _obstacleAvoidanceTypes;
            set => _obstacleAvoidanceTypes = value;
        }
    }
}
