// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class Cursor: UnityToRebelFork.Editor.BorderImage
    {
        protected static readonly RbfxAttribute<bool> UseSystemShapesAttr = new ("Use System Shapes", VariantType.VarBool, new Variant(false), _=>((Cursor)_).UseSystemShapes, (_,v)=>((Cursor)_).UseSystemShapes = v);
        protected static readonly RbfxAttribute<VariantList> ShapesAttr = new ("Shapes", VariantType.VarVariantList, new Variant(new VariantList() {  }), _=>((Cursor)_).Shapes, (_,v)=>((Cursor)_).Shapes = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return UseSystemShapesAttr;
            yield return ShapesAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _useSystemShapes = false;

        protected VariantList _shapes = new VariantList() {  };

        public bool UseSystemShapes
        {
            get => _useSystemShapes;
            set => _useSystemShapes = value;
        }

        public VariantList Shapes
        {
            get => _shapes;
            set => _shapes = value;
        }
    }
}
