// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class DragAndDropMode
    {
        public static readonly string Disabled = "Disabled";
        public static readonly string Source = "Source";
        public static readonly string Target = "Target";
        public static readonly string SourceAndTarget = "SourceAndTarget";
    }
}
