// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class DropDownList: UnityToRebelFork.Editor.Menu
    {
        protected static readonly RbfxAttribute<int> SelectionAttr = new ("Selection", VariantType.VarInt, new Variant(0), _=>((DropDownList)_).Selection, (_,v)=>((DropDownList)_).Selection = v);
        protected static readonly RbfxAttribute<bool> ResizePopupAttr = new ("Resize Popup", VariantType.VarBool, new Variant(false), _=>((DropDownList)_).ResizePopup, (_,v)=>((DropDownList)_).ResizePopup = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return SelectionAttr;
            yield return ResizePopupAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected int _selection = 0;

        protected bool _resizePopup = false;

        public int Selection
        {
            get => _selection;
            set => _selection = value;
        }

        public bool ResizePopup
        {
            get => _resizePopup;
            set => _resizePopup = value;
        }
    }
}
