// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class FaceCameraMode
    {
        public static readonly string None = "None";
        public static readonly string RotateXYZ = "Rotate XYZ";
        public static readonly string RotateY = "Rotate Y";
        public static readonly string LookAtXYZ = "LookAt XYZ";
        public static readonly string LookAtY = "LookAt Y";
        public static readonly string LookAtMixed = "LookAt Mixed";
        public static readonly string Direction = "Direction";
        public static readonly string AxisAngle = "Axis Angle";
    }
}
