// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class FillMode
    {
        public static readonly string Solid = "Solid";
        public static readonly string Wireframe = "Wireframe";
        public static readonly string Point = "Point";
    }
}
