// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class FocusMode
    {
        public static readonly string NotFocusable = "NotFocusable";
        public static readonly string ResetFocus = "ResetFocus";
        public static readonly string Focusable = "Focusable";
        public static readonly string FocusableDefocusable = "FocusableDefocusable";
    }
}
