// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class GlobalIlluminationValue
    {
        public static readonly string None = "None";
        public static readonly string UseLightMap = "Use LightMap";
        public static readonly string BlendLightProbes = "Blend Light Probes";
    }
}
