// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class HighlightMode
    {
        public static readonly string Never = "Never";
        public static readonly string Focus = "Focus";
        public static readonly string Always = "Always";
    }
}
