// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class InterpolationMode
    {
        public static readonly string Bezier = "Bezier";
        public static readonly string CatmullRom = "Catmull-Rom";
        public static readonly string Linear = "Linear";
        public static readonly string CatmullRomFull = "Catmull-Rom Full";
    }
}
