// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class LightMode
    {
        public static readonly string Realtime = "Realtime";
        public static readonly string Mixed = "Mixed";
        public static readonly string Baked = "Baked";
    }
}
