// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class LightType
    {
        public static readonly string Directional = "Directional";
        public static readonly string Spot = "Spot";
        public static readonly string Point = "Point";
    }
}
