// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class LightingMode
    {
        public static readonly string Forward = "Forward";
        public static readonly string DeferredBlinnPhong = "Deferred Blinn-Phong";
        public static readonly string DeferredPBR = "Deferred PBR";
    }
}
