// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class LightImportance
    {
        public static readonly string Auto = "Auto";
        public static readonly string Important = "Important";
        public static readonly string NotImportant = "Not Important";
    }
}
