// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class ListView: UnityToRebelFork.Editor.ScrollView
    {
        protected static readonly RbfxAttribute<string> HighlightModeAttr = new ("Highlight Mode", VariantType.VarString, new Variant(UnityToRebelFork.Editor.HighlightMode.Focus), _=>((ListView)_).HighlightMode, (_,v)=>((ListView)_).HighlightMode = v);
        protected static readonly RbfxAttribute<bool> MultiselectAttr = new ("Multiselect", VariantType.VarBool, new Variant(false), _=>((ListView)_).Multiselect, (_,v)=>((ListView)_).Multiselect = v);
        protected static readonly RbfxAttribute<bool> HierarchyModeAttr = new ("Hierarchy Mode", VariantType.VarBool, new Variant(false), _=>((ListView)_).HierarchyMode, (_,v)=>((ListView)_).HierarchyMode = v);
        protected static readonly RbfxAttribute<int> BaseIndentAttr = new ("Base Indent", VariantType.VarInt, new Variant(0), _=>((ListView)_).BaseIndent, (_,v)=>((ListView)_).BaseIndent = v);
        protected static readonly RbfxAttribute<bool> ClearSelOnDefocusAttr = new ("Clear Sel. On Defocus", VariantType.VarBool, new Variant(false), _=>((ListView)_).ClearSelOnDefocus, (_,v)=>((ListView)_).ClearSelOnDefocus = v);
        protected static readonly RbfxAttribute<bool> SelectOnClickEndAttr = new ("Select On Click End", VariantType.VarBool, new Variant(false), _=>((ListView)_).SelectOnClickEnd, (_,v)=>((ListView)_).SelectOnClickEnd = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return HighlightModeAttr;
            yield return MultiselectAttr;
            yield return HierarchyModeAttr;
            yield return BaseIndentAttr;
            yield return ClearSelOnDefocusAttr;
            yield return SelectOnClickEndAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected string _highlightMode = UnityToRebelFork.Editor.HighlightMode.Focus;

        protected bool _multiselect = false;

        protected bool _hierarchyMode = false;

        protected int _baseIndent = 0;

        protected bool _clearSelOnDefocus = false;

        protected bool _selectOnClickEnd = false;

        public string HighlightMode
        {
            get => _highlightMode;
            set => _highlightMode = value;
        }

        public bool Multiselect
        {
            get => _multiselect;
            set => _multiselect = value;
        }

        public bool HierarchyMode
        {
            get => _hierarchyMode;
            set => _hierarchyMode = value;
        }

        public int BaseIndent
        {
            get => _baseIndent;
            set => _baseIndent = value;
        }

        public bool ClearSelOnDefocus
        {
            get => _clearSelOnDefocus;
            set => _clearSelOnDefocus = value;
        }

        public bool SelectOnClickEnd
        {
            get => _selectOnClickEnd;
            set => _selectOnClickEnd = value;
        }
    }
}
