// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class LoopMode
    {
        public static readonly string Default = "Default";
        public static readonly string ForceLooped = "ForceLooped";
        public static readonly string ForceClamped = "ForceClamped";
    }
}
