// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class MaterialQuality
    {
        public static readonly string Low = "Low";
        public static readonly string Medium = "Medium";
        public static readonly string High = "High";
    }
}
