// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class Menu: UnityToRebelFork.Editor.Button
    {
        protected static readonly RbfxAttribute<IntVector2> PopupOffsetAttr = new ("Popup Offset", VariantType.VarIntVector2, new Variant(new IntVector2(0, 0)), _=>((Menu)_).PopupOffset, (_,v)=>((Menu)_).PopupOffset = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return PopupOffsetAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected IntVector2 _popupOffset = new IntVector2(0, 0);

        public IntVector2 PopupOffset
        {
            get => _popupOffset;
            set => _popupOffset = value;
        }
    }
}
