// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class ObjectAnimation: UnityToRebelFork.Editor.Resource
    {

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }
    }
}
