// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class Obstacle: UnityToRebelFork.Editor.Component
    {
        protected static readonly RbfxAttribute<float> RadiusAttr = new ("Radius", VariantType.VarFloat, new Variant(5f), _=>((Obstacle)_).Radius, (_,v)=>((Obstacle)_).Radius = v);
        protected static readonly RbfxAttribute<float> HeightAttr = new ("Height", VariantType.VarFloat, new Variant(5f), _=>((Obstacle)_).Height, (_,v)=>((Obstacle)_).Height = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return RadiusAttr;
            yield return HeightAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected float _radius = 5f;

        protected float _height = 5f;

        public float Radius
        {
            get => _radius;
            set => _radius = value;
        }

        public float Height
        {
            get => _height;
            set => _height = value;
        }
    }
}
