// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class Orientation
    {
        public static readonly string Horizontal = "Horizontal";
        public static readonly string Vertical = "Vertical";
    }
}
