// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class PartitionType
    {
        public static readonly string watershed = "watershed";
        public static readonly string monotone = "monotone";
    }
}
