// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class PostProcessAntialiasing
    {
        public static readonly string None = "None";
        public static readonly string FXAA2 = "FXAA2";
        public static readonly string FXAA3 = "FXAA3";
    }
}
