// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class ReflectionQuality
    {
        public static readonly string Vertex = "Vertex";
        public static readonly string Pixel = "Pixel";
    }
}
