// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class ReflectionMode
    {
        public static readonly string Zone = "Zone";
        public static readonly string NearestProbe = "Nearest Probe";
        public static readonly string BlendProbes = "Blend Probes";
        public static readonly string BlendProbesandZone = "Blend Probes and Zone";
    }
}
