// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class RequestedTargetType
    {
        public static readonly string None = "None";
        public static readonly string Position = "Position";
        public static readonly string Velocity = "Velocity";
    }
}
