// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class RmlCanvasComponent: UnityToRebelFork.Editor.LogicComponent
    {
        protected static readonly RbfxAttribute<ResourceRef> TextureAttr = new ("Texture", VariantType.VarResourceRef, new Variant(new ResourceRef("Texture2D", "")), _=>((RmlCanvasComponent)_).Texture, (_,v)=>((RmlCanvasComponent)_).Texture = v);
        protected static readonly RbfxAttribute<bool> RemapMousePositionAttr = new ("Remap Mouse Position", VariantType.VarBool, new Variant(true), _=>((RmlCanvasComponent)_).RemapMousePosition, (_,v)=>((RmlCanvasComponent)_).RemapMousePosition = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return TextureAttr;
            yield return RemapMousePositionAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected ResourceRef _texture = new ResourceRef("Texture2D", "");

        protected bool _remapMousePosition = true;

        public ResourceRef Texture
        {
            get => _texture;
            set => _texture = value;
        }

        public bool RemapMousePosition
        {
            get => _remapMousePosition;
            set => _remapMousePosition = value;
        }
    }
}
