// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class RmlUIComponent: UnityToRebelFork.Editor.LogicComponent
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((RmlUIComponent)_).IsEnabled, (_,v)=>((RmlUIComponent)_).IsEnabled = v);
        protected static readonly RbfxAttribute<ResourceRef> ResourceAttr = new ("Resource", VariantType.VarResourceRef, new Variant(new ResourceRef("Context", "")), _=>((RmlUIComponent)_).Resource, (_,v)=>((RmlUIComponent)_).Resource = v);
        protected static readonly RbfxAttribute<bool> UseNormalizedCoordinatesAttr = new ("Use Normalized Coordinates", VariantType.VarBool, new Variant(false), _=>((RmlUIComponent)_).UseNormalizedCoordinates, (_,v)=>((RmlUIComponent)_).UseNormalizedCoordinates = v);
        protected static readonly RbfxAttribute<Vector2> PositionAttr = new ("Position", VariantType.VarVector2, new Variant(new Vector2(0f, 0f)), _=>((RmlUIComponent)_).Position, (_,v)=>((RmlUIComponent)_).Position = v);
        protected static readonly RbfxAttribute<Vector2> SizeAttr = new ("Size", VariantType.VarVector2, new Variant(new Vector2(0f, 0f)), _=>((RmlUIComponent)_).Size, (_,v)=>((RmlUIComponent)_).Size = v);
        protected static readonly RbfxAttribute<bool> AutoSizeAttr = new ("Auto Size", VariantType.VarBool, new Variant(true), _=>((RmlUIComponent)_).AutoSize, (_,v)=>((RmlUIComponent)_).AutoSize = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return ResourceAttr;
            yield return UseNormalizedCoordinatesAttr;
            yield return PositionAttr;
            yield return SizeAttr;
            yield return AutoSizeAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected ResourceRef _resource = new ResourceRef("Context", "");

        protected bool _useNormalizedCoordinates = false;

        protected Vector2 _position = new Vector2(0f, 0f);

        protected Vector2 _size = new Vector2(0f, 0f);

        protected bool _autoSize = true;

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public ResourceRef Resource
        {
            get => _resource;
            set => _resource = value;
        }

        public bool UseNormalizedCoordinates
        {
            get => _useNormalizedCoordinates;
            set => _useNormalizedCoordinates = value;
        }

        public Vector2 Position
        {
            get => _position;
            set => _position = value;
        }

        public Vector2 Size
        {
            get => _size;
            set => _size = value;
        }

        public bool AutoSize
        {
            get => _autoSize;
            set => _autoSize = value;
        }
    }
}
