// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class Scene: UnityToRebelFork.Editor.Node
    {
        protected static readonly RbfxAttribute<float> TimeScaleAttr = new ("Time Scale", VariantType.VarFloat, new Variant(1f), _=>((Scene)_).TimeScale, (_,v)=>((Scene)_).TimeScale = v);
        protected static readonly RbfxAttribute<float> ElapsedTimeAttr = new ("Elapsed Time", VariantType.VarFloat, new Variant(0f), _=>((Scene)_).ElapsedTime, (_,v)=>((Scene)_).ElapsedTime = v);
        protected static readonly RbfxAttribute<int> NextNodeIDAttr = new ("Next Node ID", VariantType.VarInt, new Variant(1), _=>((Scene)_).NextNodeID, (_,v)=>((Scene)_).NextNodeID = v);
        protected static readonly RbfxAttribute<int> NextComponentIDAttr = new ("Next Component ID", VariantType.VarInt, new Variant(1), _=>((Scene)_).NextComponentID, (_,v)=>((Scene)_).NextComponentID = v);
        protected static readonly RbfxAttribute<string> VariableNamesAttr = new ("Variable Names", VariantType.VarString, new Variant(""), _=>((Scene)_).VariableNames, (_,v)=>((Scene)_).VariableNames = v);
        protected static readonly RbfxAttribute<ResourceRefList> LightmapsAttr = new ("Lightmaps", VariantType.VarResourceRefList, new Variant(new ResourceRefList("Texture2D") { }), _=>((Scene)_).Lightmaps, (_,v)=>((Scene)_).Lightmaps = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return TimeScaleAttr;
            yield return ElapsedTimeAttr;
            yield return NextNodeIDAttr;
            yield return NextComponentIDAttr;
            yield return VariableNamesAttr;
            yield return LightmapsAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected float _timeScale = 1f;

        protected float _elapsedTime = 0f;

        protected int _nextNodeID = 1;

        protected int _nextComponentID = 1;

        protected string _variableNames = "";

        protected ResourceRefList _lightmaps = new ResourceRefList("Texture2D") { };

        public float TimeScale
        {
            get => _timeScale;
            set => _timeScale = value;
        }

        public float ElapsedTime
        {
            get => _elapsedTime;
            set => _elapsedTime = value;
        }

        public int NextNodeID
        {
            get => _nextNodeID;
            set => _nextNodeID = value;
        }

        public int NextComponentID
        {
            get => _nextComponentID;
            set => _nextComponentID = value;
        }

        public string VariableNames
        {
            get => _variableNames;
            set => _variableNames = value;
        }

        public ResourceRefList Lightmaps
        {
            get => _lightmaps;
            set => _lightmaps = value;
        }
    }
}
