// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class ShapeType
    {
        public static readonly string Box = "Box";
        public static readonly string Sphere = "Sphere";
        public static readonly string StaticPlane = "StaticPlane";
        public static readonly string Cylinder = "Cylinder";
        public static readonly string Capsule = "Capsule";
        public static readonly string Cone = "Cone";
        public static readonly string TriangleMesh = "TriangleMesh";
        public static readonly string ConvexHull = "ConvexHull";
        public static readonly string Terrain = "Terrain";
        public static readonly string GImpactMesh = "GImpactMesh";
    }
}
