// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class SpecularQuality
    {
        public static readonly string Disabled = "Disabled";
        public static readonly string Simple = "Simple";
        public static readonly string Antialiased = "Antialiased";
    }
}
