// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class SSAOMode
    {
        public static readonly string Combine = "Combine";
        public static readonly string Preview = "Preview";
    }
}
