// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class StaticNetworkObject: UnityToRebelFork.Editor.NetworkObject
    {
        protected static readonly RbfxAttribute<ResourceRef> ClientPrefabAttr = new ("Client Prefab", VariantType.VarResourceRef, new Variant(new ResourceRef("PrefabResource", "")), _=>((StaticNetworkObject)_).ClientPrefab, (_,v)=>((StaticNetworkObject)_).ClientPrefab = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return ClientPrefabAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected ResourceRef _clientPrefab = new ResourceRef("PrefabResource", "");

        public ResourceRef ClientPrefab
        {
            get => _clientPrefab;
            set => _clientPrefab = value;
        }
    }
}
