// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class StaticModelGroup: UnityToRebelFork.Editor.StaticModel
    {
        protected static readonly RbfxAttribute<VariantList> InstanceNodesAttr = new ("Instance Nodes", VariantType.VarVariantList, new Variant(new VariantList() {  }), _=>((StaticModelGroup)_).InstanceNodes, (_,v)=>((StaticModelGroup)_).InstanceNodes = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return InstanceNodesAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected VariantList _instanceNodes = new VariantList() {  };

        public VariantList InstanceNodes
        {
            get => _instanceNodes;
            set => _instanceNodes = value;
        }
    }
}
