// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class StretchableSprite2D: UnityToRebelFork.Editor.StaticSprite2D
    {
        protected static readonly RbfxAttribute<IntRect> BorderAttr = new ("Border", VariantType.VarIntRect, new Variant(new IntRect(0, 0, 0, 0)), _=>((StretchableSprite2D)_).Border, (_,v)=>((StretchableSprite2D)_).Border = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return BorderAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected IntRect _border = new IntRect(0, 0, 0, 0);

        public IntRect Border
        {
            get => _border;
            set => _border = value;
        }
    }
}
