// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class SynchronizeRotation
    {
        public static readonly string None = "None";
        public static readonly string XYZ = "XYZ";
    }
}
