// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class TextAlignment
    {
        public static readonly string Left = "Left";
        public static readonly string Center = "Center";
        public static readonly string Right = "Right";
        public static readonly string Custom = "Custom";
    }
}
