// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class TextEffect
    {
        public static readonly string None = "None";
        public static readonly string Shadow = "Shadow";
        public static readonly string Stroke = "Stroke";
    }
}
