// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class Texture2D: UnityToRebelFork.Editor.Texture
    {

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }
    }
}
