// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class TileMap2D: UnityToRebelFork.Editor.Component
    {
        protected static readonly RbfxAttribute<bool> IsEnabledAttr = new ("Is Enabled", VariantType.VarBool, new Variant(true), _=>((TileMap2D)_).IsEnabled, (_,v)=>((TileMap2D)_).IsEnabled = v);
        protected static readonly RbfxAttribute<ResourceRef> TmxFileAttr = new ("Tmx File", VariantType.VarResourceRef, new Variant(new ResourceRef("Context", "")), _=>((TileMap2D)_).TmxFile, (_,v)=>((TileMap2D)_).TmxFile = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return IsEnabledAttr;
            yield return TmxFileAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _isEnabled = true;

        protected ResourceRef _tmxFile = new ResourceRef("Context", "");

        public bool IsEnabled
        {
            get => _isEnabled;
            set => _isEnabled = value;
        }

        public ResourceRef TmxFile
        {
            get => _tmxFile;
            set => _tmxFile = value;
        }
    }
}
