// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class ToneMappingMode
    {
        public static readonly string None = "None";
        public static readonly string Reinhard = "Reinhard";
        public static readonly string ReinhardWhite = "ReinhardWhite";
        public static readonly string Uncharted2 = "Uncharted2";
    }
}
