// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class ToolTip: UnityToRebelFork.Editor.UIElement
    {
        protected static readonly RbfxAttribute<float> DelayAttr = new ("Delay", VariantType.VarFloat, new Variant(0f), _=>((ToolTip)_).Delay, (_,v)=>((ToolTip)_).Delay = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return DelayAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected float _delay = 0f;

        public float Delay
        {
            get => _delay;
            set => _delay = value;
        }
    }
}
