// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class TrailType
    {
        public static readonly string FaceCamera = "Face Camera";
        public static readonly string Bone = "Bone";
    }
}
