// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
   public static class VertAlignment
    {
        public static readonly string Top = "Top";
        public static readonly string Center = "Center";
        public static readonly string Bottom = "Bottom";
        public static readonly string Custom = "Custom";
    }
}
