// <auto-generated />

using System.Collections.Generic;
using UnityEngine;

namespace UnityToRebelFork.Editor
{
    public partial class View3D: UnityToRebelFork.Editor.Window
    {
        protected static readonly RbfxAttribute<bool> AutoUpdateAttr = new ("Auto Update", VariantType.VarBool, new Variant(true), _=>((View3D)_).AutoUpdate, (_,v)=>((View3D)_).AutoUpdate = v);

        public override IEnumerable<RbfxAttribute> GetTypeAttributes()
        {
            yield return AutoUpdateAttr;
            foreach (var a in base.GetTypeAttributes()) yield return a;
        }

        protected bool _autoUpdate = true;

        public bool AutoUpdate
        {
            get => _autoUpdate;
            set => _autoUpdate = value;
        }
    }
}
